### ISSUE TITLE
Link multiple DLLs loaded into memory

### ISSUE THREAD

**Issue by night-codes** [jchv/go-winloader#1]
Is it possible to link multiple DLLs loaded into memory? The a.dll library uses a function from b.dll. Having packed a.dll into .go constant, we can load it from memory, but this makes no sense if it is not loaded without finding b.dll

**Comment by jchv** [comment]
I don’t think so with the current loader code, but it should be relatively easy to add it. I already have to parse both the import and export table as it is; we probably just need a sort of module cache and some logic to link to it when appropriate.

**Comment by jchv** [comment]
I have tried to add some support for your use case. I have not tested it very much. The new `AddToCache` API allows you to take a module (loaded with `LoadFromMemory` or `LoadFromFile`) and add it to the cache, at which point winloader will try to link to it first before falling back to disk.
