### ISSUE TITLE
UPX compressed DLLs

### ISSUE THREAD

**Issue by leaanthony** [jchv/go-winloader#3]
Hi there! Firstly, awesome job on the project! 

Was wondering if you had any intentions in supporting UPX compressed DLLs as there's currently an interesting trade off between shipping a compressed DLL with your application or embedding a non-compressed version that's usually 2x the size. It currently crashes with the following stack trace:

```
C:\Users\leaan\Documents\GitHub\go-winloader\cmd\demo>demo.exe tiny2.dll
Exception 0xc0000005 0x8 0x27e734414d0 0x27e734414d0
PC=0x27e734414d0

syscall.Syscall(0x27e73461310, 0x3, 0x27e73440000, 0x1, 0x0, 0x0, 0x0, 0x0)
        C:/Program Files/Go/src/runtime/syscall_windows.go:330 +0xe9
github.com/jchv/go-winloader/internal/winloader.Proc.Call(0x27e73461310, 0xc00012e330, 0x3, 0x3, 0x18, 0x8a69a0,
 0x27e73461301, 0xc00012e330)
        C:/Users/leaan/Documents/GitHub/go-winloader/internal/winloader/loader_windows.go:24 +0x22f
github.com/jchv/go-winloader/internal/memloader.(*Loader).LoadMem(0xc000162390, 0xc000168000, 0xbbea, 0xbbeb, 0x
bbeb, 0x0, 0x0, 0xc000106000)
        C:/Users/leaan/Documents/GitHub/go-winloader/internal/memloader/loader.go:239 +0xa88
github.com/jchv/go-winloader.LoadFromMemory(...)
        C:/Users/leaan/Documents/GitHub/go-winloader/loader_windows.go:25
main.main()
        C:/Users/leaan/Documents/GitHub/go-winloader/cmd/demo/main.go:18 +0x167
rax     0x27e734414d0
rbx     0x1000
rcx     0x27e73440000
rdi     0x27e73440000
rsi     0x27e7344a038
rbp     0x7ff99295bc70
rsp     0x7f359ffd48
r8      0x0
r9      0x4
r10     0x0
r11     0x246
r12     0x1
r13     0x1
r14     0x23
r15     0xffffffffffffffff
rip     0x27e734414d0
rflags  0x10206
cs      0x33
fs      0x53
gs      0x2b
```

**Comment by jchv** [comment]
Thanks for the report! I assume it is crashing at the UPX entrypoint. I'll take a look when I get a chance after work today.

**Comment by leaanthony** [comment]
Thanks! There's zero urgency for this and it's mainly curiosity.

**Comment by jchv** [comment]
I've reproduced the problem, but I'm still not really sure what's going on yet. Still, it almost definitely points to an actual bug in the loader, so it is probably worth fixing.

Of course, if all you wanted to do was save space, you could always compress the entire binary when embedding it, then decompress it at runtime.

**Comment by jchv** [comment]
I've made an effort to fix issues that were impacting UPX binaries from loading. Feel free to re-open this if you are still having issues, but I would appreciate an example binary that triggers the crash if possible.

**Comment by leaanthony** [comment]
This is amazing! Built the demo app and tested with compressed and non-compressed versions of tiny.dll. Both work. Check out the sizes:
![image](https://user-images.githubusercontent.com/1943904/125181631-1902c000-e24a-11eb-9258-f839243fee04.png)
